export const actionTypes = {
  INITIALIZATION_ITEMS: 'INITIALIZATION_ITEMS',
  INIT_USER: 'INIT_USER',
  INITIALIZATION_USERS: 'INITIALIZATION_USERS',
  ADD_ITEMS: 'ADD-ITEMS',
  DELETE_ITEMS: 'DELETE-ITEMS',
  ADD_RATING: 'ADD-RATING',
  LOGIN: 'LOGIN',
  REGISTRATION: 'REGISTRATION',
  DELETE_USERS: 'DELETE-USERS',
  REMOVE_REQUEST: 'REMOVE-REQUEST',
  CHANGE_FIRSTNAMELASTNAME: 'CHANGE_FIRSTNAME',
};
